### ISSUE TITLE
Web-Arena: Rating Key values are messed

### ISSUE THREAD

**Issue by nithyaasworld** [cloudspokes/arena-web#1015] opened 2014-11-25 05:04 UTC
Env: Windows7 Chrome39

Steps:
1. Go to https://arena.topcoder.com and login with valid user account
2. In the General chat room, expand the Rating Key
3. Scroll through it and observe

Actual:

Rating key values are one over another when scrolling. Please see that attached screenshot.

Expected:

Rating key values should be clear when scrolling down.

**Comment by skyhit** [comment] 2014-11-27 06:57
where is the screenshot?

**Comment by nithyaasworld** [comment] 2014-11-27 07:02
Please find the screenshot:

![3](https://cloud.githubusercontent.com/assets/5114190/5213347/736ea2d4-7631-11e4-99e4-478b37808acc.png)

**Comment by mdesiderio** [comment] 2014-12-11 21:15
duplicate of https://github.com/appirio-tech/arena-web/issues/1

**Closed as completed by mdesiderio** 2014-12-11 21:15 UTC
