### ISSUE TITLE
Duplicate logins when scroll.

### ISSUE THREAD

**Issue by tau0** [cloudspokes/arena-web#1112] opened 2014-12-09 15:01 UTC
Firefox 33.1

![screen shot 2014-12-09 at 18 01 10](https://cloud.githubusercontent.com/assets/6191905/5359330/6edd24fc-7fcd-11e4-9622-5b43dc722265.png)

**Comment by mdesiderio** [comment] 2014-12-11 20:06
duplicate of https://github.com/appirio-tech/arena-web/issues/1

**Closed as completed by mdesiderio** 2014-12-11 20:06 UTC
